# Generated by Django 5.2.17 on 2026-09-29 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_globalconfig'),
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='worlds.world'),
        ),
    ]
