# Generated by Django 5.2.16 on 2026-07-15 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rules', models.TextField(blank=True, default='')),
                ('lore', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'worlds',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('connections', models.JSONField(default=list)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='worlds.world')),
            ],
            options={
                'db_table': 'world_locations',
            },
        ),
    ]
