"""
Django settings for anima project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# --- Environment-based configuration (production) ---
# Alle produktiven Werte kommen aus der Umgebung (docker-compose / .env):
#   DJANGO_SECRET_KEY, DJANGO_DEBUG, DJANGO_ALLOWED_HOSTS,
#   SQLITE_PATH, REDIS_URL, CHROMA_PATH (siehe memory/services.py)
#
# Default = lokaler Dev-Betrieb (wie bei Django-Template): DEBUG=true mit
# Fallback-Schlüssel. Produktion setzt DJANGO_DEBUG=false — dann ist
# DJANGO_SECRET_KEY zwingend, sonst wird hart abgebrochen.

DEBUG = os.environ.get('DJANGO_DEBUG', 'true') == 'true'

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        # Fallback nur für lokale Entwicklung — Produktion liefert DJANGO_SECRET_KEY zwingend.
        SECRET_KEY = 'django-insecure-es*jd2+rngnj9*n$p%m9i!qavo0flsa@8w7lnjrpmhhn4*-b7c'
    else:
        from django.core.exceptions import ImproperlyConfigured

        raise ImproperlyConfigured('DJANGO_SECRET_KEY muss gesetzt sein, wenn DEBUG aus ist.')

# ALLOWED_HOSTS — env: "hostname1,hostname2" (komma-separiert)
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,0.0.0.0').split(',')
    if h.strip()
]


# Application definition
# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',  # For scheduled tasks

    # Anima Apps
    'characters',
    'anima_sessions',
    'worlds',
    'scenarios',
    'relationships',
    'memory',
    'web',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'anima.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'anima.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SQLite-Pfad: lokal im Repo, in Docker unter /data (Volume).
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('SQLITE_PATH', str(BASE_DIR / 'db.sqlite3')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# collectstatic-Ziel (wird im Docker-Entrypoint gefüllt).
# WhiteNoise: Static-Files direkt aus Gunicorn serven (kein extra nginx nötig).
# 'immutable' für versionierte Assets, mit Fallback auf Django für Fehl-Treffer.
STATIC_ROOT = BASE_DIR / 'staticfiles'
WHITENOISE_AUTOREFRESH = DEBUG  # im Dev-Modus keine Caches, in Produktion immutable

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Produktionssicherheit (nur wenn DEBUG aus) ---
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'

# --- Celery / Async Configuration ---
REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

# Default queue for tasks
CELERY_TASK_DEFAULT_QUEUE = 'default'

# Schedule for the memory consolidation task (runs nightly at 3 AM UTC)
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'consolidate-memories-nightly': {
        'task': 'web.tasks.consolidate_memories',
        'schedule': crontab(hour=3, minute=0),
    },
}
