# Generated by Django 5.2.16 on 2026-07-15 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anima_sessions', '0001_initial'),
        ('characters', '0001_initial'),
        ('scenarios', '0001_initial'),
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='characters.character'),
        ),
        migrations.AddField(
            model_name='session',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenarios.scenario'),
        ),
        migrations.AddField(
            model_name='session',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worlds.world'),
        ),
        migrations.AddField(
            model_name='sessionturn',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='anima_sessions.session'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionturn',
            unique_together={('session', 'turn_number')},
        ),
    ]
